### ISSUE TITLE
Make `maxParallelForks` custom value logging optional 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/common-custom-user-data-gradle-plugin#35]
For builds with hundreds of modules (i.e. projects), each with tests, this `maxParallelForks` logging if very noisy. 

It adds a custom value to the build scan for EVERY `test` task. 

https://github.com/gradle/common-custom-user-data-gradle-plugin/blob/980ae5c6130a6175a6cb3ad21d1f737dbb83a130/src/main/java/com/gradle/CustomBuildScanEnhancements.java#L415

Would be great is this was removed or made optional/configurable.

**Comment by bigdaz** [comment]
I think we could make this better for all users, instead of forcing users to disable it. 

I suspect that in 99% of cases we'll see the same value for `maxParallelForks` in every module. In these cases there's we only need 1 custom value. 

In the case where different modules have different values, I would suspect that the number of unique settings is still quite limited. So we could find a nice way to summarize the these few values rather than blindly adding a custom value per module.

**Comment by SimonMarquis** [comment]
Summarising could be tricky to implement correctly without losing important data.
For example, say you have a 100 modules with `maxParallelForks = 1` and 100 other with `maxParallelForks = 2`.
The "easy" solution would be to say "100 at 1" and "100" at 2, but then you don't know which one they are.
Another solution that would fit the case were only a limited amount of tasks have set a custom value, would be to simply ignore default values?
[According to the docs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks), we have a default value of 1 set by the `java` plugin.

```kotlin
doFirst { if (maxParallelForks != 1) value("$identityPath#maxParallelForks", maxParallelForks.toString()) }
```

- #230

**Comment by tylerbertrand** [comment]
The `maxParallelForks` custom value was removed in `common-custom-user-data-gradle-plugin` version [1.12](https://github.com/gradle/common-custom-user-data-gradle-plugin/releases/tag/v1.12). Instead, samples were added to the build config samples repository showing how to add this custom value to your build scans ([link](https://github.com/gradle/gradle-enterprise-build-config-samples/tree/main/build-data-capturing-gradle-samples/capture-max-parallel-forks)).
